### ISSUE TITLE
RuntimeError: Communication Exception running gen2-triangulation

### ISSUE THREAD

**Issue by madgrizzle** [luxonis/depthai-experiments#210]
Finally getting back around to trying out the face detection with stereo demo and I find that it runs fine for about 5 seconds but then crashes with the following error:

Traceback (most recent call last):
  File "main.py", line 207, in <module>
    frame = queues[i*4].get().getCvFrame()
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'mono_left' (X_LINK_ERROR)'

It only crashes when someone steps in front of the camera and face detection starts working.

**Comment by Luxonis-Brandon** [comment]
Thanks for the report and sorry for the trouble.  Not immediately sure.  But CC: @Erol444 on this.

**Comment by madgrizzle** [comment]
If it helps, it failed today with a:

>Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by Erol444** [comment]
Hello @madgrizzle , I have just pushed a small edit to latest master branch of depthai-experiments. Could you try using that + the latest `develop` branch of `depthai-python`? So checkout to develop branch and run `python3 examples/install_requirements.py` to get the latest develop version of our library. Using that seems to fix the issue. Thanks for reporting!

**Comment by madgrizzle** [comment]
Awesome, will try tonight!  Thanks for looking into it.

**Comment by madgrizzle** [comment]
It works great!  Thanks for the fix!

**Comment by madgrizzle** [comment]
Well, turns out that it just seems to work 'better', but it still crashes.  I'm not entirely sure why I wasn't getting these messages before, but I recently did an update to depthai-python.  This occurs right before the crash:

[14442C10411DC2D200] [470.453] [system] [critical] Fatal error. Please report to developers. Log: 'PoolBase' '66'
[14442C10411DC2D200] [267.191] [system] [critical] Fatal error. Please report to developers. Log: 'PoolBase' '66'
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    frame = queues[i*4].get().getCvFrame()
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'mono_left' (X_LINK_ERROR)'

**Comment by VanDavv** [comment]
@madgrizzle I'm not immediately sure why this issue occurs, will check with the team too. Could you specify which `depthai` version you're using?

**Comment by VanDavv** [comment]
@madgrizzle it appears to be a bug in the depthai itself and @themarpe managed to fix that right away (kudos!). I'll circle back once the experiment is updated with a library version containing the fix, so you'll be able to test again.

Thanks for reporting the issue!

**Comment by madgrizzle** [comment]
Just curious.. is the "bug in depthai itself" a bug in the FW or a bug in depthai-python (or something else)?

**Comment by themarpe** [comment]
@madgrizzle it was a bug in FW regarding how messages are shared across the two cores available.
More specifically some cache coherency issue.

**Comment by madgrizzle** [comment]
I spun up ubuntu 20.04 onto a RPI 4 and got everything installed and running with the same result after a few seconds. It did manage to spit out more information though:

terminate called after throwing an instance of 'dai::XLinkReadError'
  what():  Couldn't read data from stream: 'mono_left' (X_LINK_ERROR)
Stack trace (most recent call last) in thread 35627:
#6    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#5    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff7bda6573, in __cxa_throw
#4    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff7bda627f, in std::terminate()
#3    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff7bda621b, in
#2    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff7bda88cb, in __gnu_cxx::__verbose_terminate_handler()
#1    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff8c66fd67, in abort
#0    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff8c683138, in gsignal
Aborted (Signal sent by tkill() 35550 1000)
Aborted (core dumped)

**Comment by madgrizzle** [comment]
@themarpe Perhaps this should be an issue 'somewhere else' (I'll ask on discord) but it appears that the ImageManip config errors occur when resize width is less than half the height.  I was testing it at lunch and started to slowly move my hand in front of my face and the 'box' (that gets drawn on the screen) started to narrow.  When it got around half the height, the errors started to occur.  I had to get back to work but I'll do some more testing tonight and see if I can catch those events.

**Comment by SalsabilDaraghmi** [comment]
I solved this problem by modifying this line of code 
`with dai.Device(p.getOpenVINOVersion()) as device:`
to this 
`with dai.Device(p.getOpenVINOVersion() ,usb2Mode = True) as device:`
I just add usb2Mode =True
The program is working fine now without stopping
You can understand the problem that occurs from this link:
https://github.com/luxonis/depthai-python/issues/318#issuecomment-884219556

**Comment by madgrizzle** [comment]
The version on the repo still crashes for me if I make the change you described.
I then tried a version that I made that has a few extra tweaks to the ImageManip script to help reduce invalid configs that seemed to help it run better and it crashed as well.  So, I then removed all the video frame grabbing to lower the bandwidth and it still crashed under USB-3.  But when I forced it to usb2Mode, it ran stable... but after stopping it and do some other testing, it crashed.  I honestly don't know what's going on with it now.  Sometimes it just seems to stop detecting without even crashing (hanging though spewing out the "INFO" messages).

So, I keep wondering if its a hardware problem.  The more I work with it and try different things, the worse it gets. I give up, let it rest and I come back to it days later and it works better initially but then eventually craps out again and again.

**Comment by madgrizzle** [comment]
Turns out the latter problem where it seems to hang without crashing was caused by the optimizations I made.  When you don't retrieve the frames (left, right, cropped, etc.), the host program's loop runs too fast and it empties the queues of config and landmarks and only rarely gets both left and right landmarks at the same time in a single loop's iteration.  I had to slow down the loop by adding more delay to the cv2.waitkey() so that it's not emptying out the queue.

**Comment by themarpe** [comment]
Cross posting for visibility - https://github.com/luxonis/depthai-python/issues/408#issuecomment-961157245

Main issue as far as I've dug into it, is that a memory corruption is happening in a non-deterministic way, which looks like something might be wrong with the hardware, but its just that the bug is "random" and hard to pin down to a specific cause.

Will keep you posted after I discover more information about it

**Comment by szabi-luxonis** [comment]
@madgrizzle  could you try installing the following library, it contains some fixes for Script node related memory allocation:
```
python3 -m pip install -U --prefer-binary --user --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local "depthai==2.11.1.1.dev+7498afce36f34dae5482c2bbf42db317e3e53dd5"
```

Then modifying the [script](https://github.com/luxonis/depthai-experiments/blob/master/gen2-triangulation/main.py#L61) by adding the following (@alex-luxonis  [suggested](https://github.com/luxonis/depthai-python/issues/369#issuecomment-921814577) ):
`image_manip_script.setProcessor(dai.ProcessorType.LEON_CSS)`

**Comment by madgrizzle** [comment]
Knock on wood, but this so far seems pretty stable.  I've let it run for about 8 hours so far without issue on the RPI.  I'll let it run overnight and then switch to the x86 host to see how it works there.

**Comment by madgrizzle** [comment]
No problem running overnight.  I'm now trying out the script from https://github.com/luxonis/depthai-python/issues/408#issuecomment-961157245 that I modified to include facial detection/recognition.  Previously it would run for a few seconds and crash, but its been running for 15 minutes now with no issue.

**Comment by alex-luxonis** [comment]
@madgrizzle Thanks for the tests!
Was `.setProcessor(dai.ProcessorType.LEON_CSS)` added as well in the Script nodes?
If yes, could you also try removing it and see if it's still stable. Would help us in investigating any more issues when running on the default `LEON_MSS` core.

**Comment by madgrizzle** [comment]
I had done both changes.  When I go home at lunch, i'll undo the setProcessor and see what the effect is.

**Comment by madgrizzle** [comment]
@alex-luxonis Couple things.. First it appears that for the gen2-triangulation script, I did not change it to LEON_CSS (only the updated depthai).  I went ahead and set it to LEON_MSS and will let it run for a while to to be absolutely certain.  

Second, the script from https://github.com/luxonis/depthai-python/issues/408#issuecomment-961157245 with my face detection/recognition additions however did crash using LEON_MSS rather quickly (seconds to minutes) and ran for 12+ hours last night using LEON_CSS without crashing.  However, when playing around at lunch time (i.e., switching back and forth between MSS and CSS), it did crash with LEON_CSS after about a 15 minute run.  That potentially could be related to something else (like ImageManip or maybe just the process of switching the code or something).

Definite improvement running the new depthai + the script node in LEON_CSS processor.

**Comment by themarpe** [comment]
@madgrizzle thanks for extensive testing - the findings support my theory that moving to CSS only mitigates/suppresses the issue but isn't the cause of it.
We'll look into the underlying cause to resolve it properly, in the meantime the mitigation seems to be quite effective

**Comment by madgrizzle** [comment]
@themarpe seems so.. good enough for my use-case (giving my robot some vision).

**Comment by madgrizzle** [comment]
Ack.. accidentally closed.

**Comment by themarpe** [comment]
@madgrizzle in latest `develop` is a patch that should reduce the issues even further. 
`MSS` might work as expected now. 
Feel free to test in your usecase if it improved:)

**Comment by madgrizzle** [comment]
It ran gen2-triangulation pretty solid (I stopped it after 10 minutes), but then I ran it on my yoloSpatialCalculator+face recognition program that often hangs on 2.13.3 after a few minutes and this version did the same.  Never consistent on when either occurs.. sometimes a couple of minutes, sometimes after a couple of hours, butsometimes just a few seconds.

I do still notice lots of ImageManip unsupported config errors.  Any progress on addressing that (I can deal with it, nevertheless)?

**Comment by themarpe** [comment]
Thanks for testing - is your yolo + face recognition available somewhere openly? Might be a good benchmark to test against, just so that error is more easily observed.

Regarding ImageManip, we have a branch for it, but there are a couple of extra things to fixup and retest, so might take a bit more. I'll also address the issue with unsupported config errors :)

**Comment by madgrizzle** [comment]
It's currently part of a ROS node, but it won't be hard to strip it out and make it run standalone.  I should have it on my repo tonight and will post a link.

**Comment by madgrizzle** [comment]
This is my repo with the code I'm using.  https://github.com/madgrizzle/visiontest

It ran 12 hours today with no one in the room.  When I walked it, it said it detected an elephant (great for my ego) and a few minutes later it locked up while my head was down looking at my phone.  One key I've discovered to making it lock up is putting my hands to my face (like rubbing my eyes.)  It doesn't happen all the time, but so often that it has to be more than coincidence.

**Comment by themarpe** [comment]
Thanks, will try to recreate:)

**Comment by madgrizzle** [comment]
I'm current running 2.13.3.0.dev+61eb5c1617623c628fab1cc09d123073518124b0 with great success.  It ran for days using LEON_CSS until I intentionally stopped it.  I'll try out LEON_MSS as well.  I've added a few things to the pipeline since the code in the visiontest repo and moved it back into my ROS node because it appears stable enough for me (/em crosses fingers).
